---
- name: main task
  hosts: staging
  vars:
    build_root_abspath: "/home/ubuntu/build/{{ ansible_date_time.iso8601_basic_short }}"
    demobackend_version: "latest"
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    # - role: hello_world
    - role: build_fastapi
